#pragma once

enum CLIMATE{SEA, CONTINENTAL, OCEANIC, MEDITERRAN, TROPICAL, ARID, DESERT, NORDIC, POLAR};
enum RELIEF{NONE, PLAIN, ROCKY, HILLS, MOUNTAINS};
enum VEGETATION{NONE, FOREST};
enum WATER{NONE, RIVER_SMALL, RIVER_MED, RIVER_LARGE, LAKE, SWAMP};
enum WORLDOBJECT{NONE, PRIM_SPAWN};

class Region
{
	int	x,	y;
	CLIMATE	climate;
	RELIEF	relief;
	VEGETATION	vegetation;
};

